[project]
name = "library.module.essential"
version = "0.1.0"
description = "维持 Mephisto 的基本服务正常运行"
dependencies = []
authors = [
    {name = "nullqwertyuiop", email = "null@member.fsf.org"}
]

[tool.pdm]
distribution = false

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[mephisto]
name = "核心组件"
identifier = "library.module.essential"
dependencies = []
standards = []
